config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :projects do
  	resources :comments
  end
  
  root 'projects#index'
  get 'project_comments_path' => "comments#create"
  
  devise_for :project_users do
    get '/project_users/sign_out' => 'devise/sessions#destroy'
  end
  
  get 'projects/image/:id' => 'projects#image'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :comment, presence: true
    belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  validates :uri, presence: true

  has_many :comments, dependent: :destroy 
  has_one_attached :image, dependent: :destroy
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @project = Project.find(params[:project_id])
            @comment = @project.comments.create(params[:comment].permit(:name, :comment))
        redirect_to @project 
    end
  
    def destroy
        @project = Project.find(params[:project_id])
        @comment = @project.comments.find(params[:id])
        @comment.destroy
        redirect_to @project
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_project_user!, only: [:create, :update, :destroy]
  before_action :is_authorised, only: [:update, :destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all.with_attached_image
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project = Project.find(params[:id]) 
    @project.last_viewed = Time.now unless current_project_user
    @project.clicks += 1 unless current_project_user
    @project.save
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.image.attach(params[:project][:image])
    @project.user = current_project_user.email
    @project.clicks = 0
    @project.last_viewed = Time.now

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    @project.last_viewed = Time.now unless current_project_user
    @project.clicks += 1 unless current_project_user

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :uri, :data, :image) if params[:project]
    end

    def is_authorised
      redirect_to root_path, alert: "You don't have permission to modify this asset." unless current_project_user.email == @project.user
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def locate_readme(str)
        re = /(?=(https?:\/\/github.com\/(\w|[\/])*README\.?\w*))/m
        str.scan(re) do |match|
            return match[0].to_s
        end
    end

    def allow_project_modify?(project)
        return false unless current_project_user
        project.user == current_project_user.email
    end

    def create_link?(str)
        
    end

    def check_readme_str?(str)
        re = /(?=(https?:\/\/github.com\/(\w|[\/])*README\.?\w*))/m
        re.match?(str)
    end

    def remove_at(str)
        re = /(?<=)(.*)(?=(.*?)(\@\w*\.\w*))/m
        str.scan(re) do |match|
            return match[0].to_s
        end
    end
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <% if comment.name? %>
            <strong><%= comment.name %>:</strong>
          <% else %>
            <strong>Anonymous:</strong>
          <% end %>
          <%= comment.comment %>
        </p>
      </div>
    </div>
    <% if allow_project_modify?(@project) %>
     <%= link_to 'Delete', [comment.project, comment],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
    <% end %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= form_for([@project, @project.comments.build]) do |form| %>
    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
  
        <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="container">
      <div class="row">
        <div class="col-2">
          <div class="form-floating mb-3">
            <%= form.text_field :name, class: "form-control", id: "floatingInput", placeholder: "Name" %>
            <label for="floatingInput">Name</label>
          </div>
        </div>

        <div class="col-6">
          <div class="form-floating mb-3">
            <%= form.text_field :comment, class: "form-control", id: "floatingInput", placeholder: "Comment" %>
            <label for="floatingInput">Comment</label>
          </div>
        </div>
        <div class="col-1">
          <%= form.submit :submit, class: "btn btn-primary btn-sm rounded-pill", type: "submit" %>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar fixed-bottom navbar-inverse" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <div class="navbar-header navbar-bottom">
      <%= link_to 'CS300 Project Projector', '/', :class => 'navbar-brand' %>
    </div>
  </div>
</nav> 

app/views/layouts/_general.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-inverse bg-inverse fixed-top flex-row">
  <%= link_to 'CS300 Project Projector', '/', :class => 'navbar-brand p-2 justify-content-start' %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if project_user_signed_in? %>
    <div class="navbar-brand p-2 justify-content-center">Logged in as <%= current_project_user.email %></div>
  <% end %>
  <div class="navbar-collapse justify-content-end p" id="navbarNavAltMarkup">
    <% if project_user_signed_in? %>
      <%= link_to 'Edit profile', edit_project_user_registration_path, :class => 'glyphicon glyphicon-user nav-linkp', :width => "30", :height => "24" %>
      <%= link_to "Sign Out", destroy_project_user_session_path, :method => :delete, :class => 'glyphicon glyphicon-log-out nav-link', :width => "30", :height => "24"  %>
    <% else %>
      <%= link_to " Sign up", new_project_user_registration_path, :class => 'glyphicon glyphicon-user nav-link'  %>
      <%= link_to " Login", new_project_user_session_path, :class => 'glyphicon glyphicon-log-in nav-link'  %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render '/layouts/general' %>
  </head>

<%= render '/layouts/navbar' %>

<div id="wrap">
  <div id="main" class="container clear-top body">  
    <body>
      <% if notice %>
        <p class="alert alert-success" role="alert"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger" role="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </body>
  </div>
</div>

<%= render '/layouts/footer' %>

</html>

app/views/project_users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/project_users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/projects/_comment.html.erb
<section class="section comments">
    <h2 class="subtitle is-5"><strong><%= @project.comments.count %></strong> Comments</h2>
    <h3 class="subtitle is-3">Leave a reply</h3>
    <%= render partial: 'comments/form', locals: {project: @project} %>
    <div class="table">
        <ul class="list-group">
        <% @project.comments.each do |comment| %>
            <% if comment.comment %>
                <li class="list-group-item"><%= render comment %></li>
            <% end %>
        <% end %>
        </ul>
    </div>
</section>

app/views/projects/_data.html.erb
<% @project.data.split("\r\n").each do |line| %>
    <p class="text"><%= line %>
<% end %>

app/views/projects/_form.html.erb
<%= form_for project, :html => {:class => "form-horizontal"} do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label :name, "Name:", class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= form.label :uri, class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= form.url_field :uri, class: 'form-control' %>
    </div>
  </div>
  
  <div class="form-group">
    <%= form.label :image, "image:", class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= form.file_field :image, class: 'form-control', accept: 'image/png,image/gif,image/jpeg' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :data, class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= form.text_area :data, class: 'form-control', :rows => 3 %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit :submit, class: 'btn btn-success rounded-pill', type: "submit" %>
  </div>
<% end %>

app/views/projects/_show.html.erb
<section class="section">
  <div class="container-fluid">
    <div class="h2 d-inline-flex">Project:</div>
    <div class="p d-flex"><%= image_tag @project.image, class: "img-thumbnail img-small"  if @project.image.attached? %></div>
    <div class="d-flex">
      Project Name: <%= @project.name %>
    </div>
    <div class="d-flex">
      Number of Views: <%= @project.clicks %>
    </div>
    <div class="d-flex">
      URL of Project: <%= link_to @project.uri, @project.uri, :class => "btn  btn-link btn-sm" %>
    </div>
    <div class="d-flex">
      Data: <%= render '/projects/data' %>
    </div>
    <div class="d-flex">
      Last Viewed: <%= @project.last_viewed %>
    </div>
  </div>
</section>

<section class="section">
  <div class="level-right">
    <span class="h4">
        <% if allow_project_modify?(@project) %>
          <%= link_to "Edit", edit_project_path(@project), class:"btn btn-success rounded-pill" %> |
        <% end %>
        <%= link_to 'Back', projects_path, class:"btn btn-info rounded-pill" %>
    </span>
  </div>
</section>

app/views/projects/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="1" scope="col"></th>
      <th colspan="1" scope="col">Project Name</th>
      <th colspan="1" scope="col">User</th>
      <th colspan="1" scope="col"></th>
      <% if project_user_signed_in? %>
        <th colspan="2" scope="col"></th>
      <% end %>
      <th colspan="1" scope="col">Comments</th>
      <th colspan="1" scope="col">Project Link</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
      <th scope="row"></th>
        <td scope="row"><%= project.name %></td>
        <td><%= remove_at(project.try(:user)) %>
        <td><%= link_to 'Show', project %></td>
        <% if allow_project_modify?(project) %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% elsif project_user_signed_in? %>
          <th colspan="2" scope="col"></th>
        <% end %>
        <td><%= project.comments.count %> comments</td>
        <td><%= link_to project.uri[0...20], project.uri, class: "btn btn-link" %>></a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/edit.html.erb
<% content_for :title,  "Editing" %>
<h1>Editing Project</h1>

<%= render 'form', project: @project %>


<section class="section">
  <div class="level-right">
    <span class="h4 border bg-transparent rounded-pill">
        <% if allow_project_modify?(@project) %>
          <%= link_to "Show", project_path(@project), class:"btn btn-success rounded-pill" %> |
        <% end %>
        <%= link_to 'Back', projects_path, class:"btn btn-info rounded-pill" %>
    </span>
  </div>
</section>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title,  "Projects" %>

<h1 class="title">Projects</h1>

<div class="container-fluid">
    <%= render '/projects/table' %>
</div>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<% content_for :title,  "New Project" %>
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path, class:"btn btn-info rounded-pill" %>

app/views/projects/show.html.erb
<% content_for :title,  @project.name %>

<%= render '/projects/show' %>
<%= render '/projects/comment' %>